managerApp/urls.py
from django.urls import include,path
from .views import managerApp,proposal,person,term,proposalstatus,thesisstatus,thesis,defense,persontype,user,pdf


urlpatterns = [

    path('', managerApp.home, name='home'),

    path('proposals/', include(([
        path('', proposal.IndexView.as_view(), name='proposals_list'),
        path('<int:pk>/', proposal.DetailView.as_view(), name='proposals_details'),
        path('create/', proposal.CreateProposalView.as_view(), name='proposals_create'),
        path('<int:pk>/update/', proposal.UpdateProposalView.as_view(), name='proposals_update'),
        path('<int:pk>/delete/', proposal.DeleteProposalView.as_view(), name='proposals_delete')
    ], 'managerApp'), namespace='proposals')),

    path('persons/', include(([
        path('', person.IndexView.as_view(), name='persons_list'),
        path('<int:pk>/', person.DetailView.as_view(), name='persons_details'),
        path('create/', person.CreatePersonView.as_view(), name='persons_create'),
        path('<int:pk>/update/', person.UpdatePersonView.as_view(), name='persons_update'),
        path('<int:pk>/delete/', person.DeletePersonView.as_view(), name='persons_delete')
    ], 'managerApp'), namespace='persons')),

    path('term/', include(([
        path('', term.IndexView.as_view(), name='terms_list'),
        path('create/', term.CreateTermView.as_view(), name='terms_create'),
        path('<int:pk>/update/', term.UpdateTermView.as_view(), name='terms_update'),
        path('<int:pk>/delete/', term.DeleteTermView.as_view(), name='terms_delete')
    ], 'managerApp'), namespace='terms')),

    path('proposalstatus/', include(([
        path('', proposalstatus.IndexView.as_view(), name='proposal_status_list'),
        path('create/', proposalstatus.CreateProposalStatusView.as_view(), name='proposal_status_create'),
        path('<int:pk>/update/', proposalstatus.UpdateProposalStatusView.as_view(), name='proposal_status_update'),
        path('<int:pk>/delete/', proposalstatus.DeleteProposalStatusView.as_view(), name='proposal_status_delete'),
    ], 'managerApp'), namespace='proposal_status')),

    path('thesisstatus/', include(([
        path('', thesisstatus.IndexView.as_view(), name='thesis_status_list'),
        path('create/', thesisstatus.CreateThesisStatusView.as_view(), name='thesis_status_create'),
        path('<int:pk>/update/', thesisstatus.UpdateThesisStatusView.as_view(), name='thesis_status_update'),
        path('<int:pk>/delete/', thesisstatus.DeleteThesisStatusView.as_view(), name='thesis_status_delete'),
    ], 'managerApp'), namespace='thesis_status')),

    path('thesis/', include(([
        path('', thesis.IndexView.as_view(), name='thesis_list'),
        path('create/', thesis.CreateThesisView.as_view(), name='thesis_create'),
        path('<str:pk>/', thesis.DetailView.as_view(), name='thesis_details'),
        path('<str:pk>/update/', thesis.UpdateThesisView.as_view(), name='thesis_update'),
        path('<str:pk>/delete/', thesis.DeleteThesisView.as_view(), name='thesis_delete'),
    ], 'managerApp'), namespace='thesis')),

    path('defense/', include(([
        path('', defense.IndexView.as_view(), name='defense_list'),
        path('create/', defense.CreateDefenseView.as_view(), name='defense_create'),
        path('<str:pk>/', defense.DetailView.as_view(), name='defense_details'),
        path('<str:pk>/update/', defense.UpdateDefenseView.as_view(), name='defense_update'),
        path('<str:pk>/delete/', defense.DeleteDefenseView.as_view(), name='defense_delete'),
    ], 'managerApp'), namespace='defense')),

    path('persontype/', include(([
        path('', persontype.IndexView.as_view(), name='person_type_list'),
        path('create/', persontype.CreatePersonTypeView.as_view(), name='person_type_create'),
        path('<int:pk>/update/', persontype.UpdatePersonTypeView.as_view(), name='person_type_update'),
        path('<int:pk>/delete/', persontype.DeletePersonTypeView.as_view(), name='person_type_delete'),
    ], 'managerApp'), namespace='person_type')),

    path('users/', include(([
        path('', user.IndexView.as_view(), name='user_list'),
        path('create/', user.CreateUserView.as_view(), name='user_create'),
        path('<int:pk>/', user.DetailView.as_view(), name='user_details'),
        path('<int:pk>/update/', user.UpdateUserView.as_view(), name='user_update'),
        path('<int:pk>/delete/', user.DeleteUserView.as_view(), name='user_delete'),
    ], 'managerApp'), namespace='user')),

    path('reporte/', include(([
        path('propsinaprobar', proposal.PropuestasSinAprobarView.as_view(), name='propsinaprobar'),
        path('propsinaprobar/<int:pk>/', proposal.PropuestasSinAprobarDetailView.as_view(), name='propsinaprobar_details'),
        path('tgenejecucion', thesis.ThesisEnEjecucionView.as_view(), name='tgenejecucion'),
        path('defensapendiente', defense.DefensaPendienteView.as_view(), name='defensapendiente'), 
        path('actporstatus', term.ActPorStatusView.as_view(), name='actporstatus'), 
        path('asignadoaprofesor', person.SelectorDeReporteView.as_view(), name='asignadoaprofesor'), 
        path('tareasdeprofesor', person.TareasPorProfesorView.as_view(), name='tareasdeprofesor'), 
        path('actporterminologia', term.SelectorTermView.as_view(), name='actporterminologia'), 
        path('tareasporterm', term.TareasPorTermView.as_view(), name='tareasporterm'), 
        path('estadisticas', defense.TermSelectorView.as_view(), name='estadisticas'),
        path('data/estadisticas', defense.TermSelectorView.get_data, name='data_estadisticas'),
        path('logstransacciones', user.LogsTransacciones, name="log_transacciones")
    ], 'managerApp'), namespace='reporte')),

    path('pdf/', include(([
        #PDF de reportes
        path('actporterminologia',pdf.ActPorTerm.as_view(),name='pdf_actporterminologia'),
        path('actporterminologia_detalle',pdf.ActPorTermDet.as_view(),name='pdf_actporterminologiadet'),
        path('estadisticas_notas',pdf.StatsNotas.as_view(),name='pdf_estadisticas_notas'),
        path('tareasdeprofesor',pdf.TareasProfesor.as_view(),name='pdf_tareasdeprofesor'),
        path('tareasdeprofesor_detalle',pdf.TareasProfesorDetalle.as_view(),name='pdf_tareasdeprofesordet'),
        path('defensapendiente',pdf.DefensasPendientes.as_view(),name='pdf_defensapendiente'),
        path('defensapendiente_detalle',pdf.DefensasPendientesDetalle.as_view(),name='pdf_defensapendientedet'),
        path('tgenejecucion',pdf.TgEjecucion.as_view(),name='pdf_tgenejecucion'),
        path('tgenejecucion_detalle',pdf.TgEjecucionDetalle.as_view(),name='pdf_tgenejecuciondet'),
        path('propsinaprobar',pdf.PropuestasSinAprobar.as_view(),name='pdf_propsinaprobar'),
        path('propsinaprobar_detalle',pdf.PropuestasSinAprobarDetalle.as_view(),name='pdf_propsinaprobardet'),
        path('actporstatus', pdf.ActPorStatus.as_view(), name='pdf_actporstatus'), 
        path('actporstatus_detalle', pdf.ActPorStatusDetalle.as_view(), name='pdf_actporstatus_detalle'), 
        path('logstransacciones', pdf.LogsTransacciones.as_view(), name="pdf_log_transacciones"),

        #PDF de consultas
        path('proposal',pdf.ProposalIndex.as_view(),name='pdf_proposal'),
        path('person',pdf.PersonIndex.as_view(),name='pdf_person'),
        path('term',pdf.TermIndex.as_view(),name='pdf_term'),
        path('thesis',pdf.ThesisIndex.as_view(),name='pdf_thesis'),
        path('defense',pdf.DefenseIndex.as_view(),name='pdf_defense'),
    ], 'managerApp'), namespace='pdf'))

]
 

tmanager/urls.py
from django.contrib import admin
from django.urls import include,path
from managerApp.views import managerApp,proposal

urlpatterns = [
    path('', include('managerApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name="admin")
]

managerApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Proposal
from django.template import loader
from django.http import Http404

# Create your views here.

def index(request):
    latest_propuestas = Proposal.objects.order_by('-delivery_date')[:5]
    template = loader.get_template('propuestas/index.html')
    context = {
        'latest_propuestas': latest_propuestas
    }
    return HttpResponse(template.render(context, request))

def detail(request, propuesta_id):
    try:
        propuesta = Proposal.objects.get(pk=propuesta_id)
    except Propuesta.DoesNotExist:
        raise Http404("La propuesta no existe")
    return render(request, 'propuestas/detail.html', {'propuesta': propuesta})


def results(request, propuesta_id):
    response = "Está buscando los resultados de la propuesta %s."
    return HttpResponse(response % propuesta_id)

def modify(request, propuesta_id):
    return HttpResponse("Está modificando la propuesta %s." % propuesta_id)

managerApp/views/defense.py
from . import *
from django.http import JsonResponse
import statistics

# para no repetir
DEFENSE_CRUD_FIELDS = (
    "defense_date",
    "jury_1",
    "jury_2",
    "jury_suplente",
    "jury_1_assistance_confirmation",
    "jury_2_assistance_confirmation",
    "jury_suplente_assistance_confirmation",
    "tutor_assistance_confirmation",
    "grade",
    "publication_mention",
    "honorific_mention",
    "corrections_delivered",
    "top_date_corrections",
    "grade_uploaded",
    "observations",
    "thesis"
)


@method_decorator([login_required, guest_permissions], name='dispatch')
class IndexView(generic.ListView):
    template_name = 'managerApp/defense/index.html'
    context_object_name = 'defense_list'
    
    def get_queryset(self):
        return Defense.objects.order_by('thesis')


@method_decorator([login_required, guest_permissions], name='dispatch')
class DetailView(generic.DetailView):
    model = Defense
    template_name = 'managerApp/defense/detail.html'


@method_decorator([login_required, manager_permissions], name='dispatch')
class CreateDefenseView(generic.CreateView):
    model = Defense
    fields = DEFENSE_CRUD_FIELDS
    template_name = 'managerApp/defense/create.html'

    def get_form(self):
        form = super().get_form()
        form.fields['defense_date'].widget = DateTimePickerInput(
            options = {
                "format": "DD/MM/YYYY hh:mm:ss",
                "locale": "es"
            }
        )
        return form

    def form_valid(self, form):
        defense = form.save(commit=False)
        defense.save_creating()
        messages.success(self.request, 'La defensa fue creada satisfactoriamente')
        return redirect('defense:defense_list')


@method_decorator([login_required, manager_permissions], name='dispatch')
class UpdateDefenseView(generic.UpdateView):
    model = Defense
    fields = DEFENSE_CRUD_FIELDS
    template_name = 'managerApp/defense/update.html'

    def get_form(self):
        form = super().get_form()
        form.fields['defense_date'].widget = DateTimePickerInput(
            options = {
                "format": "DD/MM/YYYY hh:mm:ss",
                "locale": "es"
            }
        )
        return form

    def form_valid(self, form):
        defense = form.save(commit=False)
        defense.save()
        messages.success(self.request, 'La defensa fue actualizada satisfactoriamente')
        return redirect('defense:defense_list')


@method_decorator([login_required, manager_permissions], name='dispatch')
class DeleteDefenseView(generic.DeleteView):
    model = Defense
    template_name = 'managerApp/defense/delete.html'
    success_url = reverse_lazy('defense:defense_list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, "La defensa fue eliminada exitosamente")
        return super().delete(request, *args, **kwargs)

@method_decorator([login_required, guest_permissions], name='dispatch')
class DefensaPendienteView(generic.ListView):
    model = Defense
    template_name = 'managerApp/reporte/defensapendiente/index.html'
    context_object_name = 'defense_list'
    success_url = reverse_lazy('reporte:defensapendiente')
    paginate_by = 15
    
    def get_queryset(self):
        return Defense.objects.filter(grade__isnull=True).order_by('thesis__proposal__student_1__document_id')

@method_decorator([login_required, guest_permissions], name='dispatch')
class TermSelectorView(generic.ListView):
    model = Term
    template_name = 'managerApp/reporte/stats/index.html'
    context_object_name = 'term_list'
    success_url = reverse_lazy('reporte:estadisticas')
    paginate_by = 15
    
    def get_context_data(self, **kwargs):
        context = super(TermSelectorView, self).get_context_data(**kwargs)
        context.update({
            'terms': Person.objects.all(),
            'defensas': Defense.objects.all(),
        })
        return context

    def get_queryset(self):
        return Term.objects.all()

    def get_data(self, **kwargs):
        query = self.GET.get('l_terms', '').split(",")
        if(query[0] != ''):
            terms = Term.objects.filter(id__in=query)
        else:
            terms = Term.objects.all()
        data = {
            "terms":[],
            "notas":[],
            "media":[],
            "mediana":[],
            "moda":[],
            "desviacion":[]
            }
        for t in terms:
            data["terms"].append(t.description)
            data["notas"].append([])
            defensas = Defense.objects.filter(thesis__term=t).filter(grade__isnull=False)
            for d in defensas:
                data["notas"][-1].append(d.grade)
            if(len(data["notas"][-1]) >= 1):            
                data["media"].append(statistics.mean(data["notas"][-1])) 
                data["mediana"].append(statistics.median(data["notas"][len(data["notas"])-1]))
                try:
                    data["moda"].append(statistics.mode(data["notas"][len(data["notas"])-1]))
                except statistics.StatisticsError as e:
                    data["moda"].append(sorted(data["notas"][len(data["notas"])-1])[len(data["notas"][len(data["notas"])-1])//2 - 1])
                try:
                    data["desviacion"].append(statistics.stdev(data["notas"][len(data["notas"])-1]))
                except statistics.StatisticsError as e:
                    data["desviacion"].append([])
            else:
                data["media"].append(0)
                data["mediana"].append(0) 
                data["moda"].append(0)
                data["desviacion"].append(0)
        
        return JsonResponse(data)

managerApp/views/managerApp.py
from . import *


#Paginas principales para la aplicacion
def home(request):    
    return render(request, 'managerApp/home.html')

managerApp/views/persontype.py
from . import *


@method_decorator([login_required, admin_permissions], name='dispatch')
class IndexView(generic.ListView):
    template_name = 'managerApp/persontype/index.html'
    context_object_name = 'person_type_list'
    
    def get_queryset(self):
        return PersonType.objects.order_by('id')[:10]


@method_decorator([login_required, admin_permissions], name='dispatch')
class CreatePersonTypeView(generic.CreateView):
    model = PersonType
    fields = "__all__"
    template_name = 'managerApp/persontype/create.html'

    def form_valid(self, form):
        persontype = form.save(commit=False)
        persontype.save()
        messages.success(self.request, 'Fue creado un nuevo tipo de persona')
        return redirect('person_type:person_type_list')


@method_decorator([login_required, admin_permissions], name='dispatch')
class UpdatePersonTypeView(generic.UpdateView):
    model = PersonType
    fields = "__all__"
    template_name = 'managerApp/persontype/update.html'

    def form_valid(self, form):
        persontype = form.save(commit=False)
        persontype.save()
        messages.success(self.request, 'Fue actualizado un tipo de persona')
        return redirect('person_type:person_type_list')


@method_decorator([login_required, admin_permissions], name='dispatch')
class DeletePersonTypeView(generic.DeleteView):
    model = PersonType
    template_name = 'managerApp/persontype/delete.html'
    success_url = reverse_lazy('person_type:person_type_list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, "El tipo de persona fue eliminado exitosamente")
        return super().delete(request, *args, **kwargs)

managerApp/templates/managerApp/proposal/create.html
{% extends 'base.html' %}

{% block extrahead %}
  {{ form.media }}
{% endblock %}

{% block content %}
  <br><h4 class="mb-3">Agregando una nueva propuesta</h4>
  
  {% include './form.html' %}

  <script>
    $(document).ready(function() {
        $('.datepicker').datepicker({ format: "dd/mm/yyyy" });
    }); 
  </script>
{% endblock %}

managerApp/templates/managerApp/proposal/delete.html
{% extends 'base.html' %}
{% block content %}
{% load extra_tags %}
<form method="post">
    {% csrf_token %}
    <p>
        <br><h4 class="mb-3">Eliminando propuesta</h4>
        ¿Estas seguro de que quieres eliminar la propuesta? "{{ proposal }}"? <br>
        Se eliminarán los elementos asociados ({{ proposal|get_related_objects }})
        <div style="margin-bottom: 50px; margin-top:10px">
            <button type="submit" class="btn btn-success">guardar</button>
            <a href="{% url 'proposals:proposals_list' %}" class="btn btn-outline-secondary" role="button">
                volver
            </a>
        </div>
    </p>
</form>
{% endblock %}

managerApp/templates/managerApp/proposal/detail.html
{% extends 'base.html' %}
    
    {% block content %}
    
    <br>
    <h4>Detalle de propuesta</h4>
    
    <p>
        <br>
        <strong>Título:&nbsp;</strong> <i>{{ proposal.title }}</i><br>
        <strong>Fecha que fue entregada:&nbsp;</strong> <i>{{ proposal.delivery_date }}</i><br>
        <strong>Estatus:&nbsp;</strong> <i>{{ proposal.status }}</i><br>
        {% if not proposal.student_2 %}
            <strong>Estudiante:&nbsp;</strong> <i>{{ proposal.student_1 }}</i><br>
        {% else %}
            <strong>Estudiantes:&nbsp;</strong> <i>{{ proposal.student_1 }}</i> y <i>{{ proposal.student_1 }}</i><br>
        {% endif %}
        <strong>Tutor académico:&nbsp;</strong> <i>{{ proposal.academic_tutor }}</i><br>
        <strong>Tutor empresarial:&nbsp;</strong> <i>{{ proposal.company_tutor }}</i><br>
        <strong>Terminología:&nbsp;</strong> <i>{{ proposal.term }}</i><br>
    </p>

    <a href="{% url 'proposals:proposals_list' %}" class="btn btn-outline-secondary" role="button">
        volver
    </a>

{% endblock %}

managerApp/templates/managerApp/proposal/form.html
{% load static %}

{% load crispy_forms_tags %}

<form method="post" novalidate autocomplete="off" autocomplete="nope">
    {% csrf_token %}

    <div class="row">
 
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.title|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.status|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.student_1|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.student_2|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.academic_tutor|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.company_tutor|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.term|as_crispy_field }}
      </div>
      <div class="col-md-6 col-sm-8 col-12">
        {{ form.delivery_date|as_crispy_field }}
      </div>

      <div class="col-md-6 col-sm-8 col-12">
      <div style="margin-bottom: 50px;">
        <button type="submit" class="btn btn-success">guardar</button>
        <a href="{% url 'proposals:proposals_list' %}" class="btn btn-outline-secondary" role="button">
          volver
        </a>
      </div>
      </div>
    </div>

  </form>

managerApp/templates/managerApp/proposal/index.html
{% extends 'base.html' %}

{% block content %}


    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Propuestas</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            {% if user.is_authenticated %}
                 {% if user.is_admin or user.is_manager %}
            <a href="{% url 'proposals:proposals_create' %}" class="btn btn-outline-secondary" role="button">
                Crear propuesta
            </a>
            {% endif %}
                {% endif %}
        </div>
        <a href="/pdf/proposal" class="btn btn-outline-secondary" target="_blank">
          Exportar en pdf
        </a>
      </div>
    </div>

    {% include '../messages.html' %}


    {% if latest_propuestas %}
    
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Título</th>
                        <th>Estatus</th>
                        <th>Fecha de entrega</th>
                        {% if user.is_authenticated %}
                            {% if user.is_admin or user.is_manager %}
                            <th>Accciones</th>
                            {% endif %}
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
        {% for p in latest_propuestas %}
            <tr>
                <td>{{p.id}}</td>
                <td><a href="{% url 'proposals:proposals_details' p.id %}">{{ p.title }}</a></td>
                <td>{{p.status}}</td>
                <td>{{p.delivery_date}}</td>

                {% if user.is_authenticated %}
                 {% if user.is_admin or user.is_manager %}
                <td>
                    <a href="{% url 'proposals:proposals_update' p.id %}">Actualizar</a>
                    <a href="{% url 'proposals:proposals_delete' p.id %}">Eliminar</a>
                </td>
                {% endif %}
                {% endif %}

            </tr>
        {% endfor %}
                </tbody>
            </table>
        </div>

    {% else %}
        <p>No hay propuestas registradas.</p>
    {% endif %}

{% endblock %}

managerApp/templates/managerApp/proposal/update.html
{% extends 'base.html' %}

{% block extrahead %}
  {{ form.media }}
{% endblock %}

{% block content %}
  <br><h4 class="mb-3">Editando propuesta</h4>
  {% include './form.html'  %}
{% endblock %}